// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Test.Src.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Montar pedido")]
    public partial class MontarPedidoFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "MontarPedido.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("pt-br"), "Montar pedido", "        Sendo um cliente​ ​do sistema da pizzaria UDS, eu quero visualizar os det" +
                    "alhes do meu pedido e \n        saber o preço final e o tempo de preparo. \n      " +
                    "  O objetivo é saber o quanto irei gastar e em quanto tempo a pizza ficará pront" +
                    "a.", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Montar pedido para visualizar os detalhes do pedido")]
        public virtual void MontarPedidoParaVisualizarOsDetalhesDoPedido()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Montar pedido para visualizar os detalhes do pedido", null, ((string[])(null)));
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 14
        testRunner.Given("um cliente que deseja visualizar os detalhes do pedido montado anteriormente", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Dado ");
#line 15
        testRunner.When("sistema consulta o pedido", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Quando ");
#line 16
        testRunner.Then("o sistema apresenta o resumo do pedido listando sabor da pizza escolhida juntamen" +
                    "te com o preço", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Entao ");
#line 17
        testRunner.And("a lista de personalização que foi selecionado e seu valor", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line 18
        testRunner.And("o valor total do pedido e seu tempo de preparo", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "E ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
